### ISSUE TITLE
Server Detail on Boot from Volume Instance throws Exception

### ISSUE THREAD

**Issue by venkatnsrinivasan** [woorea/openstack-java-sdk#167]
We are using the icehouse release of openstack. When we boot the node using a volume and use the sdk to get server details , we get the exception
Can not instantiate value of type [simple type, class com.woorea.openstack.nova.model.Image] from JSON String; no single-String constructor/factory method (through reference chain: com.woorea.openstack.nova.model.Servers["servers"]->com.woorea.openstack.nova.model.Server["image"]); nested exception is org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class com.woorea.openstack.nova.model.Image] from JSON String; no single-String constructor/factory method (through reference chain: com.woorea.openstack.nova.model.Servers["servers"]->com.woorea.openstack.nova.model.Server["image"])

The image is being returned as an empty string as part of the server detail and seems like Json has issues marshalling this ?  Would adding a String constructor be the correct solution for this ?

Thanks

**Comment by aakash-cfx** [comment]
Hi, We are facing similar issue with 3.2.2. snapshot version of the SDK. Could you please share the fix?
